### ISSUE TITLE
compiled build file, getting import errors

### ISSUE THREAD

**Issue by souporserious** [mathieudutour/sketch-module-json-sync#1]
Hello 👋 awesome library! I understand this is fairly new, but I was trying to import into a gulp project I have going and was unable to do it because it says import is not defined. I'm even using `gulp.babel`. Any idea how I can get it to import correct into a gulp project? Do you think the files need to be built with babel or something in this repo? Here is the repo I'm working in https://github.com/souporserious/framer-sketch-boilerplate I'm not sure if you are familiar with FramerJS, but I wanted to try and mimic their import functionality where you can access each Sketch layer by a namespace like `app.layerName`.

**Comment by mathieudutour** [comment]
I'm not sure what framer has to do with sketch plugin development.

To use this module, you will need to use https://github.com/mathieudutour/skpm

**Comment by souporserious** [comment]
I wanted to read a Sketch file as JSON for a Framer project I'm working on. I take it I can't use your module with [Gulp](http://gulpjs.com/)?

**Comment by mathieudutour** [comment]
Just gulp, no. But with Rollup yes.

**Comment by mathieudutour** [comment]
But this module can only be used in a sketch plugin

**Comment by souporserious** [comment]
Ah I see, thank you for the explanation. I'm not too familiar with Sketch plugin development, but is it possible to trigger a Sketch plugin from a Gulp task and Rollup? So Gulp watches a Sketch file, when it has been saved it run's a plugin.

**Comment by mathieudutour** [comment]
probably yes but I don't know how. Might be worth asking here: http://sketchplugins.com/

**Comment by souporserious** [comment]
@mathieudutour amazing work on this!!! I got `skpm` up and running and was able to import this library. Only question I have now is how to get the JSON data? I have the following: 

```
import { importFromJSON, exportToJSON } from 'sketch-module-json-sync'

export default function (context) {
  const json = exportToJSON(context)
  console.log(json) // is this right?
}
```
But I get `<MOUndefined: 0x60000000f1b0>` in the console. I'm guessing I'm not doing something right?

Appreciate any guidance. This is my first time writing a Sketch plugin. I was so amazed to see this project and others you've made. Seriously, great job! Excited to see if I can make the plugin I have in mind.
